# if vim.g.neovide then
# 	vim.o.guifont = "FiraCode Nerd Font:h12"
# 	vim.g.neovide_transparency = 0.88
# 	-- vim.g.neovide_theme = "catppuccin mocha"
# 	vim.g.neovide_refresh_rate = 144
# end

 # fork = false
 # frame = "none"
 # idle = true
 # maximized = true
 # neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
 # no-multigrid = false
 # srgb = true
 # tabs = true
 # theme = "auto"
 # title-hidden = true
 # vsync = true
 # wsl = false
 #
 # [font]
 # normal = [] # Will use the bundled Fira Code Nerd Font by default
 # size = 20.0
